name = "Omega"
license = "MIT"
licenselink = "https://github.com/gethugothemes/omega-hugo-theme/blob/master/LICENSE"
description = "Omega Hugo is a modern Landing Page Template. The eye-catchy appearance will blow away your potential customer mind."
homepage = "https://gethugothemes.com/products/omega/"
demosite = "https://demo.gethugothemes.com/omega/"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'gethugothemes', 'responsive', 'clean', 'simple', 'creative', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.64.0"

[author]
  name = "Gethugothemes"
  homepage = "https://gethugothemes.com/"